pipeline {
    agent {
        docker {
            label 'docker'
            image 'mborne/postgis-integration:latest'
            args ' --network webgateway '
        }
    }
    stages {
        stage('Import dila') {
            steps {
                sh 'DEBUG=* /opt/postgis-integration/bin/import.js dila'
            }
        }
    }
}