pipeline {
    agent {
        docker {
            label 'docker'
            image 'mborne/postgis-integration:latest'
            args ' --network webgateway '
        }
    }
    stages {
        stage('Import laposte (codes-postaux)') {
            steps {
                sh 'DEBUG=* /opt/postgis-integration/bin/import.js laposte'
            }
        }
    }
}