pipeline {
    parameters {
        string(name: 'CODE_DEP', defaultValue: '25', description: 'Département à importer')
    }
    agent {
        docker {
            label 'docker'
            image 'mborne/postgis-integration:latest'
            args ' --network devbox '
        }
    }
    stages {
        stage('Import cadastre') {
            steps {
                sh "DEBUG=* /opt/postgis-integration/bin/import.js cadastre ${params.CODE_DEP}"
            }
        }
    }
}